VERSION 5.00
Object = "{24F4AB9F-37F4-43D4-B383-FB6CD721B629}#1.0#0"; "OpenGridEX20.ocx"
Object = "{F9043C88-F6F2-101A-A3C9-08002B2F49FB}#1.2#0"; "COMDLG32.OCX"
Begin VB.Form frmUnbound2 
   Caption         =   "Unbound Sample"
   ClientHeight    =   5325
   ClientLeft      =   2880
   ClientTop       =   2505
   ClientWidth     =   6090
   LinkTopic       =   "Form1"
   ScaleHeight     =   355
   ScaleMode       =   3  'Pixel
   ScaleWidth      =   406
   Begin VB.ComboBox cboView 
      Height          =   315
      Left            =   720
      Style           =   2  'Dropdown List
      TabIndex        =   2
      Top             =   45
      Width           =   2625
   End
   Begin MSComDlg.CommonDialog cdlNWind 
      Left            =   5040
      Top             =   15
      _ExtentX        =   847
      _ExtentY        =   847
      _Version        =   393216
      CancelError     =   -1  'True
      DialogTitle     =   "Where is JSNWind.mdb"
      FileName        =   "JSNWind.mdb"
      Filter          =   "Databases|*.mdb"
   End
   Begin OpenGridEX20.GridEX GridEX1 
      Height          =   4635
      Left            =   60
      TabIndex        =   0
      Top             =   495
      Width           =   5925
      _ExtentX        =   10451
      _ExtentY        =   8176
   End
   Begin VB.Label Label1 
      AutoSize        =   -1  'True
      Caption         =   "View:"
      Height          =   195
      Left            =   90
      TabIndex        =   1
      Top             =   105
      Width           =   390
   End
End
Attribute VB_Name = "frmUnbound2"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Explicit

Dim mvaraProducts As Variant
Dim mRecordCount As Long

Dim mRecordsetCols As Long

Private Sub cboView_Click()

    If cboView.ListIndex = 0 Then
        'table view
        GridEX1.View = jgexTable
    Else
        'card view
        GridEX1.View = jgexCard
    End If
    'Show the icon column only in table view
    GridEX1.Columns("Icon").Visible = (GridEX1.View = jgexTable)
End Sub






Private Sub Form_Load()
Dim i As Integer
Dim db As Database
Dim rsProducts As Recordset
Dim strFileName As String
Dim col As JSColumn
    '--- design-time state of the original, generated by tools\GenSample.ps1
    SetupUnbound2 GridEX1
    cboView.AddItem "Table view"
    cboView.AddItem "Card view"

    'set the GroupPrefix property for each column equal to its caption
    For Each col In GridEX1.Columns
        col.GroupPrefix = col.Caption & ":"
    Next
    SetFormattingConditions
    'add an icon column
    cboView.ListIndex = 0
    strFileName = App.Path & "\..\..\doc\Samples\JSNWind.mdb"
    
OpenDatabase_Proc:
On Error GoTo EH_FormLoad

    Set db = OpenDatabase(strFileName)
    Set rsProducts = db.OpenRecordset("Products", dbOpenSnapshot)
    FillSuppliersValueList db
    FillCategoryValueList db
    rsProducts.MoveLast
    'Get the number of records in recordset
    mRecordCount = rsProducts.RecordCount
    rsProducts.MoveFirst
    'Retrieve records in a module level variant array used in
    'unbound events
    mvaraProducts = rsProducts.GetRows(mRecordCount)
    mRecordsetCols = UBound(mvaraProducts, 1)
    'Set the ItemCount property of the control to the number of records.
    GridEX1.ItemCount = mRecordCount
    GridEX1.Rebind
    
    Exit Sub
    
EH_FormLoad:
    Select Case Err.Number
        Case 3024, 3044 'Couldn't Find File
            Dim strTemp As String
           
            strTemp = GetFileName(strFileName)
            If strTemp = "" Then
                Unload Me
            Else
                strFileName = strTemp
                Resume OpenDatabase_Proc
            End If
        Case Else
            MsgBox Err.Description, vbCritical
            Unload Me
    End Select
End Sub


Private Sub Form_Resize()

    On Error Resume Next
    GridEX1.Move 4, GridEX1.Top, ScaleWidth - 8, ScaleHeight - GridEX1.Top - 4
    
End Sub




Private Sub GridEX1_BeforeDelete(ByVal Cancel As OpenGridEX20.JSRetBoolean)

    If MsgBox("Are you sure you want to delete this product.", vbQuestion + vbYesNo, "Unbound Sample") = vbNo Then
        Cancel = True
    End If
    
End Sub

Private Sub GridEX1_ColumnHeaderClick(ByVal Column As OpenGridEX20.JSColumn)
Dim intSortOrder As Integer

    'get the sort order of the column clicked
    intSortOrder = Column.SortOrder
    'remove all sortkeys
    GridEX1.SortKeys.Clear
    If intSortOrder = jgexSortAscending Then
        'if the column clicked is sorted in ascending order then
        'sort it in descending order
        GridEX1.SortKeys.Add Column.Index, jgexSortDescending
    Else
        'if the column clicked is not sorted or sorted in descending
        'order then sort it in ascending order
        GridEX1.SortKeys.Add Column.Index, jgexSortAscending
    End If

End Sub

Private Sub GridEX1_GroupByBoxHeaderClick(ByVal Group As OpenGridEX20.JSGroup)

    Group.SortOrder = -Group.SortOrder
    
End Sub




Private Sub GridEX1_UnboundAddNew(ByVal NewRowBookmark As OpenGridEX20.JSRetVariant, ByVal Values As OpenGridEX20.JSRowData)
Dim i As Integer

    'Increase the record count variable
    mRecordCount = mRecordCount + 1
    'redim the array holding the grid values
    If mRecordCount = 1 Then
        ReDim mvaraProducts(0 To mRecordsetCols, 0 To mRecordCount - 1)
    Else
        ReDim Preserve mvaraProducts(0 To mRecordsetCols, 0 To mRecordCount - 1)
    End If
    'write the new values in the last record
    For i = 0 To UBound(mvaraProducts)
        mvaraProducts(i - 1, mRecordCount - 1) = Values(i)
    Next
End Sub

Private Sub GridEX1_UnboundDelete(ByVal RowIndex As Long, ByVal Bookmark As Variant)
Dim i As Long
Dim j As Integer

    'decrease the record count variable
    mRecordCount = mRecordCount - 1
    'shift the records
    For i = RowIndex - 1 To mRecordCount - 1
        For j = 0 To UBound(mvaraProducts)
            mvaraProducts(j, i) = mvaraProducts(j, i + 1)
        Next
    Next
    'redim the array
    If mRecordCount = 0 Then
        Erase mvaraProducts
    Else
        ReDim Preserve mvaraProducts(0 To UBound(mvaraProducts), 0 To mRecordCount - 1)
    End If
    
End Sub

Private Sub GridEX1_UnboundReadData(ByVal RowIndex As Long, ByVal Bookmark As Variant, ByVal Values As OpenGridEX20.JSRowData)
Dim i As Long

    'set the field values
    'Note: Values array is 1-based and mvaraProducts array is 0-based
    For i = 0 To UBound(mvaraProducts)
        Values.Value(i + 1) = mvaraProducts(i, RowIndex - 1)
    Next
    
End Sub


Private Sub GridEX1_UnboundUpdate(ByVal RowIndex As Long, ByVal Bookmark As Variant, ByVal Values As OpenGridEX20.JSRowData)
Dim i As Integer

On Error GoTo EH_UnboundUpdate

    'Decrease 1 to row index because the array is zero based
    RowIndex = RowIndex - 1
    For i = 0 To UBound(mvaraProducts)
        mvaraProducts(i - 1, RowIndex) = Values(i)
    Next
    Exit Sub
    
EH_UnboundUpdate:
    MsgBox Err.Description, vbExclamation, "Unbound Sample"
End Sub



Public Function GetFileName(strFileName As String) As String
On Error GoTo EH_GetFileName

    cdlNWind.Flags = cdlOFNExplorer Or cdlOFNFileMustExist Or cdlOFNHideReadOnly Or cdlOFNLongNames
    cdlNWind.FileName = strFileName
    cdlNWind.ShowOpen
    GetFileName = cdlNWind.FileName
    Exit Function
    
EH_GetFileName:
    MsgBox "Operation Canceled", vbCritical
    
End Function


Private Sub FillSuppliersValueList(db As Database)
Dim rsSuppliers As Recordset
Dim colSup As JSColumn
Dim vlSup  As JSValueList

    Set rsSuppliers = db.OpenRecordset("Suppliers")
    Set colSup = GridEX1.Columns("SupplierID")
    colSup.HasValueList = True
    colSup.EditType = jgexEditDropDown
    colSup.SortType = jgexSortTypeString
    Set vlSup = colSup.ValueList
    Do Until rsSuppliers.EOF
        vlSup.Add rsSuppliers![SupplierID], rsSuppliers![CompanyName]
        rsSuppliers.MoveNext
    Loop
End Sub
Private Sub FillCategoryValueList(db As Database)
Dim rsCategories As Recordset
Dim colSup As JSColumn
Dim vlSup  As JSValueList
Dim ImageIndex As Integer

    Set rsCategories = db.OpenRecordset("Categories")
    Set colSup = GridEX1.Columns("CategoryID")
    colSup.HasValueList = True
    colSup.EditType = jgexEditDropDown
    colSup.SortType = jgexSortTypeString
    Set vlSup = colSup.ValueList
    Do Until rsCategories.EOF
        ImageIndex = ImageIndex + 1
        vlSup.Add rsCategories![CategoryID], rsCategories![CategoryName], ImageIndex
        rsCategories.MoveNext
    Loop
End Sub


Private Sub SetFormattingConditions()
Dim col As JSColumn
Dim fmtCon As JSFmtCondition
    Set col = GridEX1.Columns("Discontinued")
    Set fmtCon = GridEX1.FmtConditions.Add(col.Index, jgexEqual, True)
    With fmtCon.FormatStyle
        .ForeColor = vbGrayText
        .FontStrikethru = True
    End With
    'set the Group Condition too
    With GridEX1.FmtConditions
        .ApplyGroupCondition = True
        .ShowGroupConditionCount = True
        .GroupConditionCountTitle = "Discontinued"
        Set fmtCon = .GroupCondition
    End With
    fmtCon.SetCondition col.Index, jgexEqual, True
    With fmtCon.FormatStyle
        .ForeColor = vbGrayText
        .FontStrikethru = True
    End With
    
End Sub
