VERSION 5.00
Object = "{24F4AB9F-37F4-43D4-B383-FB6CD721B629}#1.0#0"; "OpenGridEX20.ocx"
Begin VB.Form frmUnboundCol 
   Caption         =   "Unbound sample using a collection"
   ClientHeight    =   5715
   ClientLeft      =   3225
   ClientTop       =   2550
   ClientWidth     =   6570
   LinkTopic       =   "Form1"
   ScaleHeight     =   5715
   ScaleWidth      =   6570
   Begin VB.CommandButton cmdAdd 
      Caption         =   "Add a row in code"
      Height          =   495
      Left            =   120
      TabIndex        =   1
      Top             =   120
      Width           =   1695
   End
   Begin OpenGridEX20.GridEX GridEX1 
      Height          =   4935
      Left            =   120
      TabIndex        =   0
      Top             =   720
      Width           =   6375
      _ExtentX        =   11245
      _ExtentY        =   8705
   End
End
Attribute VB_Name = "frmUnboundCol"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Explicit


Dim mcData As clsRecords

Private Sub cmdAdd_Click()

    'first we add the row to the dataset
    mcData.Add "Jordan", "Michael", 38
    
    'Now adjust the ItemCount
    GridEX1.ItemCount = mcData.Count
    
End Sub

Private Sub Form_Load()
Dim colTemp As JSColumn
    '--- design-time state of the original, generated by tools\GenSample.ps1
    SetupUnboundCollection GridEX1

    'Set the Column layout (This can be done at design time
    
    GridEX1.Columns.Clear
    Set colTemp = GridEX1.Columns.Add("Last Name", jgexText, jgexEditTextBox, "LastName")
    colTemp.Width = 3000
    Set colTemp = GridEX1.Columns.Add("First Name", , , "FirstName")
    colTemp.Width = 2700
    Set colTemp = GridEX1.Columns.Add("Age", , , "Age")
    colTemp.Width = 600
    colTemp.SortType = jgexSortTypeNumeric
    
    'Redim our dataset
    'first dimension is used for columns
    'second dimension is used for rows
    Set mcData = New clsRecords
    'Filling the dataset
    mcData.Add "Smith", "John", 22
    mcData.Add "Wright", "Steven", 35
    mcData.Add "Connors", "Henry", 47
    
    'Tell GridEX how many rows you have in your dataset
    GridEX1.ItemCount = mcData.Count
    
    'See Unbound events
    
    
End Sub


Private Sub GridEX1_ColumnHeaderClick(ByVal Column As OpenGridEX20.JSColumn)
Dim grTemp As JSGroup
Dim SortOrder As jgexSortOrderConstants
    'When clicking in a column header
    
    'If column is grouped
    If Column.IsGrouped Then
        'Find the group for this column
        For Each grTemp In GridEX1.Groups
            If grTemp.ColIndex = Column.Index Then
                'do the same as clicking in the Group by box header
                GridEX1_GroupByBoxHeaderClick grTemp
                Exit For
            End If
        Next
    Else
        SortOrder = Column.SortOrder
        'Clear SortKeys
        GridEX1.SortKeys.Clear
        'Add this new sortkey
        If SortOrder = jgexSortAscending Then
            'if the column was sorted in ascending order, sort the column in descending order
            GridEX1.SortKeys.Add Column.Index, jgexSortDescending
        Else
            'if was sorted in descending order or not sorted, sort the column in ascending order
            GridEX1.SortKeys.Add Column.Index, jgexSortAscending
        End If
    End If
    
End Sub

Private Sub GridEX1_GroupByBoxHeaderClick(ByVal Group As OpenGridEX20.JSGroup)

    'When clicking in a group by box header we change SortOrder for that group
    
    Group.SortOrder = -Group.SortOrder
    
    
End Sub


Private Sub GridEX1_UnboundAddNew(ByVal NewRowBookmark As OpenGridEX20.JSRetVariant, ByVal Values As OpenGridEX20.JSRowData)

    'Add a new item in the collection
    'If Values(3) was not set change to 0
    If Len(Values(3)) = 0 Then
        Values(3) = 0
    End If
    mcData.Add Values(1), Values(2), Values(3)
    
End Sub

Private Sub GridEX1_UnboundDelete(ByVal RowIndex As Long, ByVal Bookmark As Variant)

    'Delete the item in the collection
    mcData.Remove RowIndex
    
    
End Sub


Private Sub GridEX1_UnboundReadData(ByVal RowIndex As Long, ByVal Bookmark As Variant, ByVal Values As OpenGridEX20.JSRowData)
Dim recTemp As clsRecord


    'don't worry if the grid is sorted or if the column positions are changed by the user
    Set recTemp = mcData.Item(RowIndex)
    With recTemp
        Values(1) = .LastName
        Values(2) = .FirstName
        Values(3) = .Age
    End With
    
End Sub


Private Sub GridEX1_UnboundUpdate(ByVal RowIndex As Long, ByVal Bookmark As Variant, ByVal Values As OpenGridEX20.JSRowData)
Dim recTemp As clsRecord

    Set recTemp = mcData.Item(RowIndex)
    With recTemp
        .LastName = Values(1)
        .FirstName = Values(2)
        .Age = Values(3)
    End With
    
End Sub


